[package]
name = "enjarify-rs"
version = "1.0.3"
authors = [""]

[dependencies]
byteorder = "1.3.4"
futures = "0.1"
futures-cpupool = "0.1"
getopts = "0.2.21"
lazy_static = "1.4.0"
rust-crypto = "0.2.36"
zip = "0.5.8"
